### ISSUE TITLE
Please check if anything wrong with my setup. Thanks!

### ISSUE THREAD

**Issue by olivergiangvu** [Woahai321/SeerrBridge#1]
olivergiangvu@homedocker:~/SeerrBridge$ python3 seerrbridge.py
/home/olivergiangvu/SeerrBridge/seerrbridge.py:1145: DeprecationWarning: 
        on_event is deprecated, use lifespan event handlers instead.

        Read more about it in the
        [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
        
  @app.on_event("startup")
INFO:     Started server process [832732]
INFO:     Waiting for application startup.
2024-11-26 15:45:10.904 | INFO     | __main__:startup_event:1148 - Starting SeerrBridge...
2024-11-26 15:45:10.906 | ERROR    | __main__:check_and_refresh_access_token:214 - Access token is not set. Requesting a new token.
2024-11-26 15:45:10.907 | INFO     | __main__:refresh_access_token:145 - Requesting a new access token with the refresh token.
2024-11-26 15:45:11.825 | ERROR    | __main__:refresh_access_token:173 - Failed to refresh access token: Unknown error
2024-11-26 15:45:11.827 | INFO     | __main__:initialize_browser:238 - Starting persistent browser session.
2024-11-26 15:45:13.328 | SUCCESS  | __main__:initialize_browser:254 - Initialized Selenium WebDriver.
2024-11-26 15:45:14.376 | SUCCESS  | __main__:initialize_browser:258 - Navigated to Debrid Media Manager start page.
2024-11-26 15:45:15.049 | INFO     | __main__:initialize_browser:264 - Set Real-Debrid credentials in local storage.
2024-11-26 15:45:15.683 | SUCCESS  | __main__:initialize_browser:268 - Refreshed the page to apply local storage values.
2024-11-26 15:45:15.684 | INFO     | __main__:login:219 - Initiating login process.
2024-11-26 15:45:16.058 | INFO     | __main__:login:227 - Clicked on 'Login with Real Debrid' button.
2024-11-26 15:45:16.059 | INFO     | __main__:initialize_browser:274 - Attempting to click the '⚙️ Settings' link.
2024-11-26 15:45:26.492 | ERROR    | __main__:initialize_browser:310 - Error while interacting with the settings popup: Message: 
Stacktrace:
#0 0x55d134e8031a <unknown>
#1 0x55d1349966e0 <unknown>
#2 0x55d1349e53e6 <unknown>
#3 0x55d1349e5681 <unknown>
#4 0x55d134a2ab04 <unknown>
#5 0x55d134a0948d <unknown>
#6 0x55d134a27ed7 <unknown>
#7 0x55d134a09203 <unknown>
#8 0x55d1349d7cc0 <unknown>
#9 0x55d1349d8c9e <unknown>
#10 0x55d134e4dd0b <unknown>
#11 0x55d134e51c92 <unknown>
#12 0x55d134e3ab3c <unknown>
#13 0x55d134e52807 <unknown>
#14 0x55d134e200df <unknown>
#15 0x55d134e6f578 <unknown>
#16 0x55d134e6f740 <unknown>
#17 0x55d134e7f196 <unknown>
#18 0x7f9322396ac3 <unknown>

2024-11-26 15:45:26.494 | INFO     | __main__:initialize_browser:313 - Navigating to the library section.
2024-11-26 15:45:29.086 | INFO     | __main__:initialize_browser:324 - Library loading.
2024-11-26 15:45:29.088 | INFO     | __main__:initialize_browser:327 - Waiting for 2 seconds on the library page.
2024-11-26 15:45:31.092 | SUCCESS  | __main__:initialize_browser:329 - Completed waiting on the library page.
2024-11-26 15:45:31.094 | INFO     | __main__:startup_event:1163 - Started request processing task.
2024-11-26 15:45:31.098 | INFO     | __main__:schedule_token_refresh:1142 - Scheduled token refresh every 10 minutes.
Do you want to start the initial check and recurring task? (y/n): 2024-11-26 15:45:41.111 | INFO     | __main__:startup_event:1184 - Initial check and recurring task were skipped by user input.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
y
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [832732]

**Comment by Woahai321** [comment]
@olivergiangvu it appears to be having an issue finding the settings button.

Either its not logging in properly using your tokens from DMM, or there is a Popup like the expiry popup, blocking the settings button (to set a filter).

Can you run this out of headless mode and test?

Comment this headless line out

![image](https://github.com/user-attachments/assets/dae72fe2-63a2-4561-97c2-fe9bec301e76)

like this

![image](https://github.com/user-attachments/assets/d9dec704-428d-448e-b7c2-1ac42cf5760f)

**Comment by Woahai321** [comment]
BTW, I have updated the code and the headless option has moved to the .env file

**Comment by KRadd1221** [comment]
I'm having this same issue, running without headless gets me stuck at a cloudflare page trying to verify my humanity

**Comment by Woahai321** [comment]
Closing this due to inactivity. We have made further releases that can hopefully remedy some of these issues.

If you continue to experience issues, please let us know!

**Comment by rsousa88** [comment]
This is still happening in v0.4. Here's the log since startup:

Looks like something is blocking the login (?), I cannot be sure as I cannot run it in non-headless mode, but probably the cloudflare captcha.

INFO:     Started server process [1]
INFO:     Waiting for application startup.
2025-01-03 23:00:29.811 | INFO     | seerrbridge:startup_event:1507 - Starting SeerrBridge...
2025-01-03 23:00:29.811 | INFO     | seerrbridge:check_and_refresh_access_token:208 - Access token will expire on: 2025-01-04 11:47:08
2025-01-03 23:00:29.812 | INFO     | seerrbridge:check_and_refresh_access_token:215 - Access token is still valid.
2025-01-03 23:00:29.812 | INFO     | seerrbridge:initialize_browser:253 - Starting persistent browser session.
2025-01-03 23:00:29.812 | INFO     | seerrbridge:initialize_browser:257 - Detected operating system: linux
2025-01-03 23:00:29.813 | INFO     | seerrbridge:initialize_browser:263 - Detected Linux environment inside Docker. Applying Linux-specific configurations.
2025-01-03 23:00:29.813 | INFO     | seerrbridge:initialize_browser:296 - Using WebDriver Manager for dynamic ChromeDriver downloads.
2025-01-03 23:00:36.964 | SUCCESS  | seerrbridge:initialize_browser:311 - Initialized Selenium WebDriver with WebDriver Manager.
2025-01-03 23:00:41.243 | SUCCESS  | seerrbridge:initialize_browser:314 - Navigated to Debrid Media Manager page.
2025-01-03 23:00:41.359 | INFO     | seerrbridge:initialize_browser:323 - Set Real-Debrid credentials in local storage.
2025-01-03 23:00:41.968 | INFO     | seerrbridge:login:222 - Initiating login process.
2025-01-03 23:00:47.161 | WARNING  | seerrbridge:login:237 - 'Login with Real Debrid' button not found or already bypassed. Proceeding...
2025-01-03 23:00:47.162 | SUCCESS  | seerrbridge:initialize_browser:328 - Refreshed the page to apply local storage values.
2025-01-03 23:00:47.162 | INFO     | seerrbridge:initialize_browser:333 - Attempting to click the '⚙️ Settings' link.
2025-01-03 23:00:48.389 | ERROR    | seerrbridge:startup_event:1516 - Failed to initialize browser: Message: element click intercepted: Element <span>...</span> is not clickable at point (783, 330). Other element would receive the click: <div aria-labelledby="swal2-title" aria-describedby="swal2-html-container" class="swal2-popup swal2-modal swal2-icon-warning swal2-show" tabindex="-1" role="dialog" aria-live="assertive" aria-modal="true" style="display: grid;">...</div>
  (Session info: chrome=131.0.6778.69)
Stacktrace:
#0 0x563d9707f8fa <unknown>
#1 0x563d96b90d20 <unknown>
#2 0x563d96be6766 <unknown>
#3 0x563d96be46cd <unknown>
#4 0x563d96be1de5 <unknown>
#5 0x563d96be0fa8 <unknown>
#6 0x563d96bd4765 <unknown>
#7 0x563d96c03af2 <unknown>
#8 0x563d96bd40a8 <unknown>
#9 0x563d96c03cbe <unknown>
#10 0x563d96c22560 <unknown>
#11 0x563d96c03893 <unknown>
#12 0x563d96bd230d <unknown>
#13 0x563d96bd332e <unknown>
#14 0x563d9704c00b <unknown>
#15 0x563d9704ff97 <unknown>
#16 0x563d9703871c <unknown>
#17 0x563d97050b17 <unknown>
#18 0x563d9701d6cf <unknown>
#19 0x563d9706e6b8 <unknown>
#20 0x563d9706e880 <unknown>
#21 0x563d9707e776 <unknown>
#22 0x7f8426c051c4 <unknown>
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8777 (Press CTRL+C to quit)
INFO:     127.0.0.1:46226 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:46236 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:46266 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:46282 - "GET / HTTP/1.1" 404 Not Found
